[tool.poetry]
name = "exasol-sphinx-github-pages-generator"
version = "0.1.0"
description = "Generates Sphinx GitHub pages for a given Git Repository"

license = "MIT"

authors = [
    "Marlene Kreß <marlene.kress@exasol.com>"
]

readme = 'README.rst'

repository = "https://github.com/exasol/sphinx-github-pages-generator"
homepage = "https://github.com/exasol/sphinx-github-pages-generator"

keywords = ['exasol', 'github pages', 'documentaion']

[tool.poetry.dependencies]
python = ">=3.6.1,<4.0"


[tool.poetry.dev-dependencies]
Sphinx = "^3.5.3"
poethepoet = "^0.10.0"
pytest = "^6.1.1"
myst-parser = "^0.14.0"


[tool.poe.tasks]
deploy_pages_main = { shell = """
                    cd $(git rev-parse --show-toplevel)/doc;
                    python3 ./exasol_sphinx_github_pages_generator/deploy_github_pages.py
                            --target_branch "github-pages/main" --push_origin "origin" --push_enabled "push"
                            --source_branch "main"  --module_path ['../exasol_sphinx_github_pages_generator']
                            --source_dir $PWD""" }

test =  "pytest tests"
#python3 ./exasol_sphinx_github_pages_generator/deploy_github_pages.py --target_branch "github-pages/main" --push_origin "origin" --push_enabled "commit" --source_branch "main"  --module_path "['../exasol_sphinx_github_pages_generator']" --source_dir $PWD