[tool.poetry]
name = "exasol-sphinx-github-pages-generator"
version = "0.1.0"
description = "Generates Sphinx GitHub pages for a given Git Repository"

license = "MIT"

authors = [
    "Marlene Kreß <marlene.kress@exasol.com>"
]

readme = 'README.rst'

repository = "https://github.com/exasol/sphinx-github-pages-generator"
homepage = "https://github.com/exasol/sphinx-github-pages-generator"

keywords = ['exasol', 'github pages', 'documentaion']

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
Sphinx = "^3.5.3"
poethepoet = "^0.10.0"
myst-parser = "^0.14.0"

[tool.poetry.dev-dependencies]
pytest = "^6.1.1"


[tool.poe.tasks]
commit_pages_main = { shell = """cd $(git rev-parse --show-toplevel);declare -a StringArray=("../exasol_sphinx_github_pages_generator" ); python3 ./exasol_sphinx_github_pages_generator/deploy_github_pages.py --target_branch "github-pages/main" --push_origin "origin" --push_enabled "commit" --source_branch "main"  --module_path "${StringArray[@]}" --source_dir $PWD""" }
commit_pages_current = { shell = """cd $(git rev-parse --show-toplevel);declare -a StringArray=("../exasol_sphinx_github_pages_generator" ); python3 ./exasol_sphinx_github_pages_generator/deploy_github_pages.py --target_branch "github-pages/"$(git branch --show-current)"" --push_origin "origin" --push_enabled "commit" --module_path "${StringArray[@]}" --source_dir $PWD""" }
push_pages_main = { shell = """cd $(git rev-parse --show-toplevel);declare -a StringArray=("../exasol_sphinx_github_pages_generator" ); python3 ./exasol_sphinx_github_pages_generator/deploy_github_pages.py --target_branch "github-pages/main" --push_origin "origin" --push_enabled "push" --source_branch "main"  --module_path "${StringArray[@]}" --source_dir $PWD""" }
push_pages_current = { shell = """cd $(git rev-parse --show-toplevel);declare -a StringArray=("../exasol_sphinx_github_pages_generator" ); python3 ./exasol_sphinx_github_pages_generator/deploy_github_pages.py --target_branch "github-pages/"$(git branch --show-current)"" --push_origin "origin" --push_enabled "push" --module_path "${StringArray[@]}" --source_dir $PWD""" }

test =  "pytest tests"
