name: Check if versions are consistent

on:
  workflow_call:
  pull_request:

jobs:
  check-version-numbers:
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets
        run: echo $CI_USER_NAME | base64
        env:
          CI_USER_NAME: ${{ secrets.EXA_CI_USER_NAME }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.8.0

      - name: Check Release
        run: ./scripts/build/check_release.sh
