name: Release Droid - Upload GitHub Release Assets

on:
  workflow_dispatch:
    inputs:
      upload_url:
        description: 'Upload URL'
        required: true

jobs:
  check-release:
    uses: ./.github/workflows/check_version.yaml

  run_tests:
    uses: ./.github/workflows/pytest.yml
    with:
      workflow-call-ckeck: true
    secrets:
      # Machine user private access token
      MAuserPAT-workflow-call: ${{ secrets.EXA_CI_TOKEN_FOR_ADDING_AUTOMATIC_DOCUMENTATION }}
      # Machine user name
      MAuserName-workflow-call: ${{ secrets.EXA_CI_USER_NAME }}

  upload:
    needs: [run_tests, check-release]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: 1.8.0

    - name: Build Release
      run: |
        bash ./scripts/build/build_release.sh

    - name: Upload assets to the GitHub release draft
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ github.event.inputs.upload_url }}
        asset_path: dist/*

