name: test-secrets

on:
  push:
  # This way it only triggers on branch pushes,
  # and ignores releases that push a tag.
      branches:
      - '**'

jobs:
  check-release:
    uses: ./.github/workflows/check_version.yaml

  run_tests:
    uses: ./.github/workflows/pytest.yml
    with:
      workflow-call-ckeck: true
    secrets:
      MAuserPAT-workflow-call: ${{ secrets.EXA_CI_TOKEN_FOR_ADDING_AUTOMATIC_DOCUMENTATION }}
      MAuserName-workflow-call: ${{ secrets.EXA_CI_USER_NAME }}

  finish:
    needs: [run_tests, check-release]
    runs-on: ubuntu-latest
    steps:
    - name: print
      run: echo Success

